### ISSUE TITLE
Reference lists - Can we use setvalue for this

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#1]

**Comment by raghu-bhandi** [comment]
setValue action sets a specific value because an expression would always evaluate to a Value.
What is a Reference list and what are you trying to do?

**Comment by archetana** [comment]
By reference list, I mean static lists  - which may be used to populate  a drop down

**Comment by raghu-bhandi** [comment]
createSheet action has been added as a new feature for this purpose. This allows you to create a data-sheet at run time using constants that are known at run time as well as fields that are known at run time.
This feature has been tested with the help of tutorial.createSheet.xml. I tested it for success as well as failure(meaning getting desired error messages) by interactively changing this file. Applicaiton.java has a main method that allows you to run any service in the IDE.

On an aside, it is better to use cached responses for hard-coded response like values for list service instead of hard-coding values in a service.
