### ISSUE TITLE
We need to file to configure custom properties at the application level, that can capture environment variables/path etc. This will be useful when migrating to different environments 

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#12]

**Comment by raghu-bhandi** [comment]
would be quite useful if you can make a quick list of possible parameters. That will help in designing this feature.

**Comment by archetana** [comment]
Primarily it will be path variables, connection string, which will be different based on the deployment environment

**Comment by raghu-bhandi** [comment]
Simplity uses settings from application.xml. In that, only the attachmentsFolderPath may require such a facility. In fact, even this parameter is used by the default assistant. This assistant, being a Java class, can directly use the configuration utility.

Our view is that there is no point in providing another layer on top of what is available to java anyways. Let us know if there is any specific case where it would be better to have a Simplity utility rather than using the Java infrastructure.

**Comment by archetana** [comment]
Handling thru maven
