### ISSUE TITLE
Multiple schema support - related code changes are not available here, please share

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#13]

**Comment by raghu-bhandi** [comment]
It is there.Here is the description for "how To". Please raise another issue on how to and use the text below as answer and close both :-)

An application may use multiple schemas. In fact, they can use multiple data bases instances. Choose the most commonly used schema as "default". In application.xml file, provide connection details for this schema.
 
Use <schemaDetails> tag to provide details of other schemas that are used in the application. This tag allows you to specify name and the connection credentials for each of them.

In your service.xml,  you may choose the schema that you want to work with as schemaName="" attribute to specify the non-defautll schema to be used by this service.

In case you are writing your custom code, either as ServiceInterface or otherwise, DbHandler has appropriate method for you to choose the schema.
