### ISSUE TITLE
With the new file upload and download the filenames and filetype information is lost, do we need to store this seperately 

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#22]

**Comment by raghu-bhandi** [comment]
yes. the service has been down-graded to manage just the contents. This forms the core service around which we can build value-added services as and when need arises. We had to do this because we could not determine if the cost of carrying the additional info like fileName,mimeType was worth. 

We should be able to provide higher-level services quickly when we know the exact needs.

**Comment by archetana** [comment]
Fixed in JS
