### ISSUE TITLE
Include Localization and Internationalization use case in the demo

### ISSUE THREAD

**Issue by archetana** [simplity/simplity#40]

**Comment by raghu-bhandi** [comment]
Simplity is meant for service design and implementation, and not for rendering data. Localization and Internationalization aspects of an application are carefully separated from the core service design, so that they are added on a need basis at any time, without having to touch the core services of your application.

Messages originating from service that are meant for client are in English by default. Pluggable adapters are used to translate this for client's locale by a common component managed by ClientAgent (a Simplity Component) This approach is very similar to the traditional resource-bundle for different languages.

Date-with-time are ALWAYS sent as UTC, and are saved/managed as UTC. Dates with no time components are time-zone insensitive.

Other aspects like date format, currency etc.. are expected to be handled by the client-application.
